[config]
skip_core_tasks = true

[tasks.clean]
script = '''
fvm flutter clean
'''

[tasks.install]
script = '''
fvm flutter pub get
'''

[tasks.fvm-install]
script = '''
fvm install
'''

[tasks.format]
script = '''
fvm dart format lib test
'''

[tasks.run]
script = '''
fvm flutter run
'''

[tasks.generate]
script = '''
fvm flutter pub run build_runner watch --delete-conflicting-outputs
'''

[tasks.test]
script = '''
fvm flutter test --coverage
'''

[tasks.lint]
dependencies = ["format"]
script = '''
fvm flutter analyze
'''
